CREATE TABLE PIZZA_ITEMS(ID INT AUTO_INCREMENT PRIMARY KEY,Name VARCHAR(40),Type VARCHAR(20),Category VARCHAR(30),Description VARCHAR(120));
CREATE TABLE PIZZA_PRICING(ID INT AUTO_INCREMENT PRIMARY KEY, ITEMID INT REFERENCES PIZZA_Items, SIZES VARCHAR(20), Price DOUBLE);
CREATE TABLE `pizza_customers` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(30) DEFAULT NULL,
  `Password` varchar(15) DEFAULT NULL,
  `Mobile` varchar(15) DEFAULT NULL,
  `Address` varchar(60) DEFAULT NULL,
  `Email` varchar(40) DEFAULT NULL,
  `admin` tinyint DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE PIZZA_ORDERS(ID INT AUTO_INCREMENT PRIMARY KEY,CustomerId INT,OrderTime DATETIME, STATUS VARCHAR(12));
CREATE TABLE PIZZA_ORDERDETAILS(ID INT AUTO_INCREMENT PRIMARY KEY, OrderId INT REFERENCES PIZZA_Orders, PRICEID INT REFERENCES PIZZA_Pricing);
